#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoAd.Admin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="coad_test")]
	public partial class dsCoAdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertClientDeviceGroup(ClientDeviceGroup instance);
    partial void UpdateClientDeviceGroup(ClientDeviceGroup instance);
    partial void DeleteClientDeviceGroup(ClientDeviceGroup instance);
    partial void InsertTypeParams(TypeParams instance);
    partial void UpdateTypeParams(TypeParams instance);
    partial void DeleteTypeParams(TypeParams instance);
    partial void InsertClientServers(ClientServers instance);
    partial void UpdateClientServers(ClientServers instance);
    partial void DeleteClientServers(ClientServers instance);
    partial void InsertClientStores(ClientStores instance);
    partial void UpdateClientStores(ClientStores instance);
    partial void DeleteClientStores(ClientStores instance);
    partial void InsertDeviceEvent(DeviceEvent instance);
    partial void UpdateDeviceEvent(DeviceEvent instance);
    partial void DeleteDeviceEvent(DeviceEvent instance);
    partial void InsertDeviceGroupDependency(DeviceGroupDependency instance);
    partial void UpdateDeviceGroupDependency(DeviceGroupDependency instance);
    partial void DeleteDeviceGroupDependency(DeviceGroupDependency instance);
    partial void InsertDeviceGroupParams(DeviceGroupParams instance);
    partial void UpdateDeviceGroupParams(DeviceGroupParams instance);
    partial void DeleteDeviceGroupParams(DeviceGroupParams instance);
    partial void InsertDeviceParams(DeviceParams instance);
    partial void UpdateDeviceParams(DeviceParams instance);
    partial void DeleteDeviceParams(DeviceParams instance);
    partial void InsertClientDevices(ClientDevices instance);
    partial void UpdateClientDevices(ClientDevices instance);
    partial void DeleteClientDevices(ClientDevices instance);
    #endregion
		
		public dsCoAdDataContext() : 
				base(global::CoAd.Admin.Properties.Settings.Default.coad_testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dsCoAdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsCoAdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsCoAdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dsCoAdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClientDeviceGroup> ClientDeviceGroup
		{
			get
			{
				return this.GetTable<ClientDeviceGroup>();
			}
		}
		
		public System.Data.Linq.Table<TypeParams> TypeParams
		{
			get
			{
				return this.GetTable<TypeParams>();
			}
		}
		
		public System.Data.Linq.Table<ClientServers> ClientServers
		{
			get
			{
				return this.GetTable<ClientServers>();
			}
		}
		
		public System.Data.Linq.Table<ClientStores> ClientStores
		{
			get
			{
				return this.GetTable<ClientStores>();
			}
		}
		
		public System.Data.Linq.Table<DeviceEvent> DeviceEvent
		{
			get
			{
				return this.GetTable<DeviceEvent>();
			}
		}
		
		public System.Data.Linq.Table<DeviceGroupDependency> DeviceGroupDependency
		{
			get
			{
				return this.GetTable<DeviceGroupDependency>();
			}
		}
		
		public System.Data.Linq.Table<DeviceGroupParams> DeviceGroupParams
		{
			get
			{
				return this.GetTable<DeviceGroupParams>();
			}
		}
		
		public System.Data.Linq.Table<DeviceParams> DeviceParams
		{
			get
			{
				return this.GetTable<DeviceParams>();
			}
		}
		
		public System.Data.Linq.Table<ClientDevices> ClientDevices
		{
			get
			{
				return this.GetTable<ClientDevices>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientDeviceGroup")]
	public partial class ClientDeviceGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_server;
		
		private System.Nullable<int> _fo_id_group;
		
		private string _name;
		
		private int _state;
		
		private System.Nullable<System.DateTime> _dateOfChange;
		
		private EntitySet<DeviceGroupParams> _DeviceGroupParams;
		
		private EntitySet<ClientDevices> _ClientDevices;
		
		private EntityRef<ClientServers> _ClientServers;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_serverChanging(System.Nullable<int> value);
    partial void Onid_serverChanged();
    partial void Onfo_id_groupChanging(System.Nullable<int> value);
    partial void Onfo_id_groupChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    partial void OndateOfChangeChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfChangeChanged();
    #endregion
		
		public ClientDeviceGroup()
		{
			this._DeviceGroupParams = new EntitySet<DeviceGroupParams>(new Action<DeviceGroupParams>(this.attach_DeviceGroupParams), new Action<DeviceGroupParams>(this.detach_DeviceGroupParams));
			this._ClientDevices = new EntitySet<ClientDevices>(new Action<ClientDevices>(this.attach_ClientDevices), new Action<ClientDevices>(this.detach_ClientDevices));
			this._ClientServers = default(EntityRef<ClientServers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_server", DbType="Int")]
		public System.Nullable<int> id_server
		{
			get
			{
				return this._id_server;
			}
			set
			{
				if ((this._id_server != value))
				{
					if (this._ClientServers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_serverChanging(value);
					this.SendPropertyChanging();
					this._id_server = value;
					this.SendPropertyChanged("id_server");
					this.Onid_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fo_id_group", DbType="Int")]
		public System.Nullable<int> fo_id_group
		{
			get
			{
				return this._fo_id_group;
			}
			set
			{
				if ((this._fo_id_group != value))
				{
					this.Onfo_id_groupChanging(value);
					this.SendPropertyChanging();
					this._fo_id_group = value;
					this.SendPropertyChanged("fo_id_group");
					this.Onfo_id_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOfChange
		{
			get
			{
				return this._dateOfChange;
			}
			set
			{
				if ((this._dateOfChange != value))
				{
					this.OndateOfChangeChanging(value);
					this.SendPropertyChanging();
					this._dateOfChange = value;
					this.SendPropertyChanged("dateOfChange");
					this.OndateOfChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDeviceGroup_DeviceGroupParams", Storage="_DeviceGroupParams", ThisKey="id", OtherKey="id_group")]
		public EntitySet<DeviceGroupParams> DeviceGroupParams
		{
			get
			{
				return this._DeviceGroupParams;
			}
			set
			{
				this._DeviceGroupParams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDeviceGroup_ClientDevices", Storage="_ClientDevices", ThisKey="id", OtherKey="id_group")]
		public EntitySet<ClientDevices> ClientDevices
		{
			get
			{
				return this._ClientDevices;
			}
			set
			{
				this._ClientDevices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientDeviceGroup", Storage="_ClientServers", ThisKey="id_server", OtherKey="id", IsForeignKey=true)]
		public ClientServers ClientServers
		{
			get
			{
				return this._ClientServers.Entity;
			}
			set
			{
				ClientServers previousValue = this._ClientServers.Entity;
				if (((previousValue != value) 
							|| (this._ClientServers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientServers.Entity = null;
						previousValue.ClientDeviceGroup.Remove(this);
					}
					this._ClientServers.Entity = value;
					if ((value != null))
					{
						value.ClientDeviceGroup.Add(this);
						this._id_server = value.id;
					}
					else
					{
						this._id_server = default(Nullable<int>);
					}
					this.SendPropertyChanged("ClientServers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceGroupParams(DeviceGroupParams entity)
		{
			this.SendPropertyChanging();
			entity.ClientDeviceGroup = this;
		}
		
		private void detach_DeviceGroupParams(DeviceGroupParams entity)
		{
			this.SendPropertyChanging();
			entity.ClientDeviceGroup = null;
		}
		
		private void attach_ClientDevices(ClientDevices entity)
		{
			this.SendPropertyChanging();
			entity.ClientDeviceGroup = this;
		}
		
		private void detach_ClientDevices(ClientDevices entity)
		{
			this.SendPropertyChanging();
			entity.ClientDeviceGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypeParams")]
	public partial class TypeParams : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_type;
		
		private string _name;
		
		private string _mnem_param;
		
		private int _object_str_param;
		
		private string _description;
		
		private int _type_param;
		
		private int _unused;
		
		private System.Nullable<int> _object_param;
		
		private EntitySet<DeviceGroupParams> _DeviceGroupParams;
		
		private EntitySet<DeviceParams> _DeviceParams;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_typeChanging(int value);
    partial void Onid_typeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onmnem_paramChanging(string value);
    partial void Onmnem_paramChanged();
    partial void Onobject_str_paramChanging(int value);
    partial void Onobject_str_paramChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ontype_paramChanging(int value);
    partial void Ontype_paramChanged();
    partial void OnunusedChanging(int value);
    partial void OnunusedChanged();
    partial void Onobject_paramChanging(System.Nullable<int> value);
    partial void Onobject_paramChanged();
    #endregion
		
		public TypeParams()
		{
			this._DeviceGroupParams = new EntitySet<DeviceGroupParams>(new Action<DeviceGroupParams>(this.attach_DeviceGroupParams), new Action<DeviceGroupParams>(this.detach_DeviceGroupParams));
			this._DeviceParams = new EntitySet<DeviceParams>(new Action<DeviceParams>(this.attach_DeviceParams), new Action<DeviceParams>(this.detach_DeviceParams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_type
		{
			get
			{
				return this._id_type;
			}
			set
			{
				if ((this._id_type != value))
				{
					this.Onid_typeChanging(value);
					this.SendPropertyChanging();
					this._id_type = value;
					this.SendPropertyChanged("id_type");
					this.Onid_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnem_param", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mnem_param
		{
			get
			{
				return this._mnem_param;
			}
			set
			{
				if ((this._mnem_param != value))
				{
					this.Onmnem_paramChanging(value);
					this.SendPropertyChanging();
					this._mnem_param = value;
					this.SendPropertyChanged("mnem_param");
					this.Onmnem_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_str_param", DbType="Int NOT NULL")]
		public int object_str_param
		{
			get
			{
				return this._object_str_param;
			}
			set
			{
				if ((this._object_str_param != value))
				{
					this.Onobject_str_paramChanging(value);
					this.SendPropertyChanging();
					this._object_str_param = value;
					this.SendPropertyChanged("object_str_param");
					this.Onobject_str_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_param", DbType="Int NOT NULL")]
		public int type_param
		{
			get
			{
				return this._type_param;
			}
			set
			{
				if ((this._type_param != value))
				{
					this.Ontype_paramChanging(value);
					this.SendPropertyChanging();
					this._type_param = value;
					this.SendPropertyChanged("type_param");
					this.Ontype_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unused", DbType="Int NOT NULL")]
		public int unused
		{
			get
			{
				return this._unused;
			}
			set
			{
				if ((this._unused != value))
				{
					this.OnunusedChanging(value);
					this.SendPropertyChanging();
					this._unused = value;
					this.SendPropertyChanged("unused");
					this.OnunusedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_param", DbType="Int")]
		public System.Nullable<int> object_param
		{
			get
			{
				return this._object_param;
			}
			set
			{
				if ((this._object_param != value))
				{
					this.Onobject_paramChanging(value);
					this.SendPropertyChanging();
					this._object_param = value;
					this.SendPropertyChanged("object_param");
					this.Onobject_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypeParams_DeviceGroupParams", Storage="_DeviceGroupParams", ThisKey="id_type", OtherKey="id_type")]
		public EntitySet<DeviceGroupParams> DeviceGroupParams
		{
			get
			{
				return this._DeviceGroupParams;
			}
			set
			{
				this._DeviceGroupParams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypeParams_DeviceParams", Storage="_DeviceParams", ThisKey="id_type", OtherKey="id_type")]
		public EntitySet<DeviceParams> DeviceParams
		{
			get
			{
				return this._DeviceParams;
			}
			set
			{
				this._DeviceParams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceGroupParams(DeviceGroupParams entity)
		{
			this.SendPropertyChanging();
			entity.TypeParams = this;
		}
		
		private void detach_DeviceGroupParams(DeviceGroupParams entity)
		{
			this.SendPropertyChanging();
			entity.TypeParams = null;
		}
		
		private void attach_DeviceParams(DeviceParams entity)
		{
			this.SendPropertyChanging();
			entity.TypeParams = this;
		}
		
		private void detach_DeviceParams(DeviceParams entity)
		{
			this.SendPropertyChanging();
			entity.TypeParams = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientServers")]
	public partial class ClientServers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _identifier;
		
		private string _name;
		
		private string _configuration;
		
		private System.Nullable<int> _status;
		
		private EntitySet<ClientDeviceGroup> _ClientDeviceGroup;
		
		private EntitySet<ClientStores> _ClientStores;
		
		private EntitySet<ClientDevices> _ClientDevices;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidentifierChanging(string value);
    partial void OnidentifierChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnconfigurationChanging(string value);
    partial void OnconfigurationChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public ClientServers()
		{
			this._ClientDeviceGroup = new EntitySet<ClientDeviceGroup>(new Action<ClientDeviceGroup>(this.attach_ClientDeviceGroup), new Action<ClientDeviceGroup>(this.detach_ClientDeviceGroup));
			this._ClientStores = new EntitySet<ClientStores>(new Action<ClientStores>(this.attach_ClientStores), new Action<ClientStores>(this.detach_ClientStores));
			this._ClientDevices = new EntitySet<ClientDevices>(new Action<ClientDevices>(this.attach_ClientDevices), new Action<ClientDevices>(this.detach_ClientDevices));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this.OnidentifierChanging(value);
					this.SendPropertyChanging();
					this._identifier = value;
					this.SendPropertyChanged("identifier");
					this.OnidentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_configuration", DbType="NVarChar(MAX)")]
		public string configuration
		{
			get
			{
				return this._configuration;
			}
			set
			{
				if ((this._configuration != value))
				{
					this.OnconfigurationChanging(value);
					this.SendPropertyChanging();
					this._configuration = value;
					this.SendPropertyChanged("configuration");
					this.OnconfigurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientDeviceGroup", Storage="_ClientDeviceGroup", ThisKey="id", OtherKey="id_server")]
		public EntitySet<ClientDeviceGroup> ClientDeviceGroup
		{
			get
			{
				return this._ClientDeviceGroup;
			}
			set
			{
				this._ClientDeviceGroup.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientStores", Storage="_ClientStores", ThisKey="id", OtherKey="id_server")]
		public EntitySet<ClientStores> ClientStores
		{
			get
			{
				return this._ClientStores;
			}
			set
			{
				this._ClientStores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientDevices", Storage="_ClientDevices", ThisKey="id", OtherKey="id_server")]
		public EntitySet<ClientDevices> ClientDevices
		{
			get
			{
				return this._ClientDevices;
			}
			set
			{
				this._ClientDevices.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ClientDeviceGroup(ClientDeviceGroup entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = this;
		}
		
		private void detach_ClientDeviceGroup(ClientDeviceGroup entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = null;
		}
		
		private void attach_ClientStores(ClientStores entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = this;
		}
		
		private void detach_ClientStores(ClientStores entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = null;
		}
		
		private void attach_ClientDevices(ClientDevices entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = this;
		}
		
		private void detach_ClientDevices(ClientDevices entity)
		{
			this.SendPropertyChanging();
			entity.ClientServers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientStores")]
	public partial class ClientStores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_server;
		
		private int _fo_id_store;
		
		private string _name;
		
		private string _egais_props;
		
		private string _ofd_props;
		
		private string _bpa_props;
		
		private int _state;
		
		private System.Nullable<System.DateTime> _dateOfChange;
		
		private EntityRef<ClientServers> _ClientServers;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_serverChanging(int value);
    partial void Onid_serverChanged();
    partial void Onfo_id_storeChanging(int value);
    partial void Onfo_id_storeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onegais_propsChanging(string value);
    partial void Onegais_propsChanged();
    partial void Onofd_propsChanging(string value);
    partial void Onofd_propsChanged();
    partial void Onbpa_propsChanging(string value);
    partial void Onbpa_propsChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    partial void OndateOfChangeChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfChangeChanged();
    #endregion
		
		public ClientStores()
		{
			this._ClientServers = default(EntityRef<ClientServers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_server", DbType="Int NOT NULL")]
		public int id_server
		{
			get
			{
				return this._id_server;
			}
			set
			{
				if ((this._id_server != value))
				{
					if (this._ClientServers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_serverChanging(value);
					this.SendPropertyChanging();
					this._id_server = value;
					this.SendPropertyChanged("id_server");
					this.Onid_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fo_id_store", DbType="Int NOT NULL")]
		public int fo_id_store
		{
			get
			{
				return this._fo_id_store;
			}
			set
			{
				if ((this._fo_id_store != value))
				{
					this.Onfo_id_storeChanging(value);
					this.SendPropertyChanging();
					this._fo_id_store = value;
					this.SendPropertyChanged("fo_id_store");
					this.Onfo_id_storeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_egais_props", DbType="NVarChar(MAX)")]
		public string egais_props
		{
			get
			{
				return this._egais_props;
			}
			set
			{
				if ((this._egais_props != value))
				{
					this.Onegais_propsChanging(value);
					this.SendPropertyChanging();
					this._egais_props = value;
					this.SendPropertyChanged("egais_props");
					this.Onegais_propsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ofd_props", DbType="NVarChar(MAX)")]
		public string ofd_props
		{
			get
			{
				return this._ofd_props;
			}
			set
			{
				if ((this._ofd_props != value))
				{
					this.Onofd_propsChanging(value);
					this.SendPropertyChanging();
					this._ofd_props = value;
					this.SendPropertyChanged("ofd_props");
					this.Onofd_propsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bpa_props", DbType="NVarChar(MAX)")]
		public string bpa_props
		{
			get
			{
				return this._bpa_props;
			}
			set
			{
				if ((this._bpa_props != value))
				{
					this.Onbpa_propsChanging(value);
					this.SendPropertyChanging();
					this._bpa_props = value;
					this.SendPropertyChanged("bpa_props");
					this.Onbpa_propsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOfChange
		{
			get
			{
				return this._dateOfChange;
			}
			set
			{
				if ((this._dateOfChange != value))
				{
					this.OndateOfChangeChanging(value);
					this.SendPropertyChanging();
					this._dateOfChange = value;
					this.SendPropertyChanged("dateOfChange");
					this.OndateOfChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientStores", Storage="_ClientServers", ThisKey="id_server", OtherKey="id", IsForeignKey=true)]
		public ClientServers ClientServers
		{
			get
			{
				return this._ClientServers.Entity;
			}
			set
			{
				ClientServers previousValue = this._ClientServers.Entity;
				if (((previousValue != value) 
							|| (this._ClientServers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientServers.Entity = null;
						previousValue.ClientStores.Remove(this);
					}
					this._ClientServers.Entity = value;
					if ((value != null))
					{
						value.ClientStores.Add(this);
						this._id_server = value.id;
					}
					else
					{
						this._id_server = default(int);
					}
					this.SendPropertyChanged("ClientServers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceEvent")]
	public partial class DeviceEvent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_device;
		
		private string _data;
		
		private EntityRef<ClientDevices> _ClientDevices;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_deviceChanging(int value);
    partial void Onid_deviceChanged();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    #endregion
		
		public DeviceEvent()
		{
			this._ClientDevices = default(EntityRef<ClientDevices>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_device", DbType="Int NOT NULL")]
		public int id_device
		{
			get
			{
				return this._id_device;
			}
			set
			{
				if ((this._id_device != value))
				{
					if (this._ClientDevices.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_deviceChanging(value);
					this.SendPropertyChanging();
					this._id_device = value;
					this.SendPropertyChanged("id_device");
					this.Onid_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="NVarChar(MAX)")]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDevices_DeviceEvent", Storage="_ClientDevices", ThisKey="id_device", OtherKey="id", IsForeignKey=true)]
		public ClientDevices ClientDevices
		{
			get
			{
				return this._ClientDevices.Entity;
			}
			set
			{
				ClientDevices previousValue = this._ClientDevices.Entity;
				if (((previousValue != value) 
							|| (this._ClientDevices.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientDevices.Entity = null;
						previousValue.DeviceEvent.Remove(this);
					}
					this._ClientDevices.Entity = value;
					if ((value != null))
					{
						value.DeviceEvent.Add(this);
						this._id_device = value.id;
					}
					else
					{
						this._id_device = default(int);
					}
					this.SendPropertyChanged("ClientDevices");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceGroupDependency")]
	public partial class DeviceGroupDependency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_primary_group;
		
		private int _id_secondary_group;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_primary_groupChanging(int value);
    partial void Onid_primary_groupChanged();
    partial void Onid_secondary_groupChanging(int value);
    partial void Onid_secondary_groupChanged();
    #endregion
		
		public DeviceGroupDependency()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_primary_group", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_primary_group
		{
			get
			{
				return this._id_primary_group;
			}
			set
			{
				if ((this._id_primary_group != value))
				{
					this.Onid_primary_groupChanging(value);
					this.SendPropertyChanging();
					this._id_primary_group = value;
					this.SendPropertyChanged("id_primary_group");
					this.Onid_primary_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_secondary_group", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_secondary_group
		{
			get
			{
				return this._id_secondary_group;
			}
			set
			{
				if ((this._id_secondary_group != value))
				{
					this.Onid_secondary_groupChanging(value);
					this.SendPropertyChanging();
					this._id_secondary_group = value;
					this.SendPropertyChanged("id_secondary_group");
					this.Onid_secondary_groupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceGroupParams")]
	public partial class DeviceGroupParams : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_type;
		
		private int _id_group;
		
		private string _value;
		
		private int _state;
		
		private System.Nullable<System.DateTime> _dateOfChange;
		
		private EntityRef<TypeParams> _TypeParams;
		
		private EntityRef<ClientDeviceGroup> _ClientDeviceGroup;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_typeChanging(int value);
    partial void Onid_typeChanged();
    partial void Onid_groupChanging(int value);
    partial void Onid_groupChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    partial void OndateOfChangeChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfChangeChanged();
    #endregion
		
		public DeviceGroupParams()
		{
			this._TypeParams = default(EntityRef<TypeParams>);
			this._ClientDeviceGroup = default(EntityRef<ClientDeviceGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_type
		{
			get
			{
				return this._id_type;
			}
			set
			{
				if ((this._id_type != value))
				{
					if (this._TypeParams.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_typeChanging(value);
					this.SendPropertyChanging();
					this._id_type = value;
					this.SendPropertyChanged("id_type");
					this.Onid_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_group", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_group
		{
			get
			{
				return this._id_group;
			}
			set
			{
				if ((this._id_group != value))
				{
					if (this._ClientDeviceGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_groupChanging(value);
					this.SendPropertyChanging();
					this._id_group = value;
					this.SendPropertyChanged("id_group");
					this.Onid_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOfChange
		{
			get
			{
				return this._dateOfChange;
			}
			set
			{
				if ((this._dateOfChange != value))
				{
					this.OndateOfChangeChanging(value);
					this.SendPropertyChanging();
					this._dateOfChange = value;
					this.SendPropertyChanged("dateOfChange");
					this.OndateOfChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypeParams_DeviceGroupParams", Storage="_TypeParams", ThisKey="id_type", OtherKey="id_type", IsForeignKey=true)]
		public TypeParams TypeParams
		{
			get
			{
				return this._TypeParams.Entity;
			}
			set
			{
				TypeParams previousValue = this._TypeParams.Entity;
				if (((previousValue != value) 
							|| (this._TypeParams.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TypeParams.Entity = null;
						previousValue.DeviceGroupParams.Remove(this);
					}
					this._TypeParams.Entity = value;
					if ((value != null))
					{
						value.DeviceGroupParams.Add(this);
						this._id_type = value.id_type;
					}
					else
					{
						this._id_type = default(int);
					}
					this.SendPropertyChanged("TypeParams");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDeviceGroup_DeviceGroupParams", Storage="_ClientDeviceGroup", ThisKey="id_group", OtherKey="id", IsForeignKey=true)]
		public ClientDeviceGroup ClientDeviceGroup
		{
			get
			{
				return this._ClientDeviceGroup.Entity;
			}
			set
			{
				ClientDeviceGroup previousValue = this._ClientDeviceGroup.Entity;
				if (((previousValue != value) 
							|| (this._ClientDeviceGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientDeviceGroup.Entity = null;
						previousValue.DeviceGroupParams.Remove(this);
					}
					this._ClientDeviceGroup.Entity = value;
					if ((value != null))
					{
						value.DeviceGroupParams.Add(this);
						this._id_group = value.id;
					}
					else
					{
						this._id_group = default(int);
					}
					this.SendPropertyChanged("ClientDeviceGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeviceParams")]
	public partial class DeviceParams : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_device;
		
		private int _id_type;
		
		private string _value;
		
		private EntityRef<TypeParams> _TypeParams;
		
		private EntityRef<ClientDevices> _ClientDevices;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_deviceChanging(int value);
    partial void Onid_deviceChanged();
    partial void Onid_typeChanging(int value);
    partial void Onid_typeChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    #endregion
		
		public DeviceParams()
		{
			this._TypeParams = default(EntityRef<TypeParams>);
			this._ClientDevices = default(EntityRef<ClientDevices>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_device", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_device
		{
			get
			{
				return this._id_device;
			}
			set
			{
				if ((this._id_device != value))
				{
					if (this._ClientDevices.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_deviceChanging(value);
					this.SendPropertyChanging();
					this._id_device = value;
					this.SendPropertyChanged("id_device");
					this.Onid_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_type
		{
			get
			{
				return this._id_type;
			}
			set
			{
				if ((this._id_type != value))
				{
					if (this._TypeParams.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_typeChanging(value);
					this.SendPropertyChanging();
					this._id_type = value;
					this.SendPropertyChanged("id_type");
					this.Onid_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TypeParams_DeviceParams", Storage="_TypeParams", ThisKey="id_type", OtherKey="id_type", IsForeignKey=true)]
		public TypeParams TypeParams
		{
			get
			{
				return this._TypeParams.Entity;
			}
			set
			{
				TypeParams previousValue = this._TypeParams.Entity;
				if (((previousValue != value) 
							|| (this._TypeParams.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TypeParams.Entity = null;
						previousValue.DeviceParams.Remove(this);
					}
					this._TypeParams.Entity = value;
					if ((value != null))
					{
						value.DeviceParams.Add(this);
						this._id_type = value.id_type;
					}
					else
					{
						this._id_type = default(int);
					}
					this.SendPropertyChanged("TypeParams");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDevices_DeviceParams", Storage="_ClientDevices", ThisKey="id_device", OtherKey="id", IsForeignKey=true)]
		public ClientDevices ClientDevices
		{
			get
			{
				return this._ClientDevices.Entity;
			}
			set
			{
				ClientDevices previousValue = this._ClientDevices.Entity;
				if (((previousValue != value) 
							|| (this._ClientDevices.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientDevices.Entity = null;
						previousValue.DeviceParams.Remove(this);
					}
					this._ClientDevices.Entity = value;
					if ((value != null))
					{
						value.DeviceParams.Add(this);
						this._id_device = value.id;
					}
					else
					{
						this._id_device = default(int);
					}
					this.SendPropertyChanged("ClientDevices");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClientDevices")]
	public partial class ClientDevices : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _id_server;
		
		private int _fo_id_device;
		
		private int _type_device;
		
		private System.Nullable<int> _id_group;
		
		private string _name;
		
		private string _data;
		
		private string _settings;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<int> _state;
		
		private System.Nullable<System.DateTime> _dateOfChange;
		
		private EntitySet<DeviceEvent> _DeviceEvent;
		
		private EntitySet<DeviceParams> _DeviceParams;
		
		private EntityRef<ClientServers> _ClientServers;
		
		private EntityRef<ClientDeviceGroup> _ClientDeviceGroup;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_serverChanging(int value);
    partial void Onid_serverChanged();
    partial void Onfo_id_deviceChanging(int value);
    partial void Onfo_id_deviceChanged();
    partial void Ontype_deviceChanging(int value);
    partial void Ontype_deviceChanged();
    partial void Onid_groupChanging(System.Nullable<int> value);
    partial void Onid_groupChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    partial void OnsettingsChanging(string value);
    partial void OnsettingsChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    partial void OndateOfChangeChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfChangeChanged();
    #endregion
		
		public ClientDevices()
		{
			this._DeviceEvent = new EntitySet<DeviceEvent>(new Action<DeviceEvent>(this.attach_DeviceEvent), new Action<DeviceEvent>(this.detach_DeviceEvent));
			this._DeviceParams = new EntitySet<DeviceParams>(new Action<DeviceParams>(this.attach_DeviceParams), new Action<DeviceParams>(this.detach_DeviceParams));
			this._ClientServers = default(EntityRef<ClientServers>);
			this._ClientDeviceGroup = default(EntityRef<ClientDeviceGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_server", DbType="Int NOT NULL")]
		public int id_server
		{
			get
			{
				return this._id_server;
			}
			set
			{
				if ((this._id_server != value))
				{
					if (this._ClientServers.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_serverChanging(value);
					this.SendPropertyChanging();
					this._id_server = value;
					this.SendPropertyChanged("id_server");
					this.Onid_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fo_id_device", DbType="Int NOT NULL")]
		public int fo_id_device
		{
			get
			{
				return this._fo_id_device;
			}
			set
			{
				if ((this._fo_id_device != value))
				{
					this.Onfo_id_deviceChanging(value);
					this.SendPropertyChanging();
					this._fo_id_device = value;
					this.SendPropertyChanged("fo_id_device");
					this.Onfo_id_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_device", DbType="Int NOT NULL")]
		public int type_device
		{
			get
			{
				return this._type_device;
			}
			set
			{
				if ((this._type_device != value))
				{
					this.Ontype_deviceChanging(value);
					this.SendPropertyChanging();
					this._type_device = value;
					this.SendPropertyChanged("type_device");
					this.Ontype_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_group", DbType="Int")]
		public System.Nullable<int> id_group
		{
			get
			{
				return this._id_group;
			}
			set
			{
				if ((this._id_group != value))
				{
					if (this._ClientDeviceGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_groupChanging(value);
					this.SendPropertyChanging();
					this._id_group = value;
					this.SendPropertyChanged("id_group");
					this.Onid_groupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="NVarChar(MAX)")]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settings", DbType="NVarChar(MAX)")]
		public string settings
		{
			get
			{
				return this._settings;
			}
			set
			{
				if ((this._settings != value))
				{
					this.OnsettingsChanging(value);
					this.SendPropertyChanging();
					this._settings = value;
					this.SendPropertyChanged("settings");
					this.OnsettingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int")]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfChange", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateOfChange
		{
			get
			{
				return this._dateOfChange;
			}
			set
			{
				if ((this._dateOfChange != value))
				{
					this.OndateOfChangeChanging(value);
					this.SendPropertyChanging();
					this._dateOfChange = value;
					this.SendPropertyChanged("dateOfChange");
					this.OndateOfChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDevices_DeviceEvent", Storage="_DeviceEvent", ThisKey="id", OtherKey="id_device")]
		public EntitySet<DeviceEvent> DeviceEvent
		{
			get
			{
				return this._DeviceEvent;
			}
			set
			{
				this._DeviceEvent.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDevices_DeviceParams", Storage="_DeviceParams", ThisKey="id", OtherKey="id_device")]
		public EntitySet<DeviceParams> DeviceParams
		{
			get
			{
				return this._DeviceParams;
			}
			set
			{
				this._DeviceParams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientServers_ClientDevices", Storage="_ClientServers", ThisKey="id_server", OtherKey="id", IsForeignKey=true)]
		public ClientServers ClientServers
		{
			get
			{
				return this._ClientServers.Entity;
			}
			set
			{
				ClientServers previousValue = this._ClientServers.Entity;
				if (((previousValue != value) 
							|| (this._ClientServers.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientServers.Entity = null;
						previousValue.ClientDevices.Remove(this);
					}
					this._ClientServers.Entity = value;
					if ((value != null))
					{
						value.ClientDevices.Add(this);
						this._id_server = value.id;
					}
					else
					{
						this._id_server = default(int);
					}
					this.SendPropertyChanged("ClientServers");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ClientDeviceGroup_ClientDevices", Storage="_ClientDeviceGroup", ThisKey="id_group", OtherKey="id", IsForeignKey=true)]
		public ClientDeviceGroup ClientDeviceGroup
		{
			get
			{
				return this._ClientDeviceGroup.Entity;
			}
			set
			{
				ClientDeviceGroup previousValue = this._ClientDeviceGroup.Entity;
				if (((previousValue != value) 
							|| (this._ClientDeviceGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ClientDeviceGroup.Entity = null;
						previousValue.ClientDevices.Remove(this);
					}
					this._ClientDeviceGroup.Entity = value;
					if ((value != null))
					{
						value.ClientDevices.Add(this);
						this._id_group = value.id;
					}
					else
					{
						this._id_group = default(Nullable<int>);
					}
					this.SendPropertyChanged("ClientDeviceGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceEvent(DeviceEvent entity)
		{
			this.SendPropertyChanging();
			entity.ClientDevices = this;
		}
		
		private void detach_DeviceEvent(DeviceEvent entity)
		{
			this.SendPropertyChanging();
			entity.ClientDevices = null;
		}
		
		private void attach_DeviceParams(DeviceParams entity)
		{
			this.SendPropertyChanging();
			entity.ClientDevices = this;
		}
		
		private void detach_DeviceParams(DeviceParams entity)
		{
			this.SendPropertyChanging();
			entity.ClientDevices = null;
		}
	}
}
#pragma warning restore 1591
