#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoAd.Fo.Core.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="frontdk_stand_test")]
	public partial class FrontdkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGroup_device(Group_device instance);
    partial void UpdateGroup_device(Group_device instance);
    partial void DeleteGroup_device(Group_device instance);
    partial void InsertDevice(Device instance);
    partial void UpdateDevice(Device instance);
    partial void DeleteDevice(Device instance);
    partial void InsertStr_cash_param(Str_cash_param instance);
    partial void UpdateStr_cash_param(Str_cash_param instance);
    partial void DeleteStr_cash_param(Str_cash_param instance);
    partial void InsertCash_param(Cash_param instance);
    partial void UpdateCash_param(Cash_param instance);
    partial void DeleteCash_param(Cash_param instance);
    partial void InsertClassif_depart(Classif_depart instance);
    partial void UpdateClassif_depart(Classif_depart instance);
    partial void DeleteClassif_depart(Classif_depart instance);
    #endregion
		
		public FrontdkDataContext() : 
				base(global::CoAd.Fo.Core.Properties.Settings.Default.frontdk_stand_testConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FrontdkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrontdkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrontdkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrontdkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Group_device> Group_devices
		{
			get
			{
				return this.GetTable<Group_device>();
			}
		}
		
		public System.Data.Linq.Table<Device> Devices
		{
			get
			{
				return this.GetTable<Device>();
			}
		}
		
		public System.Data.Linq.Table<Str_cash_param> Str_cash_params
		{
			get
			{
				return this.GetTable<Str_cash_param>();
			}
		}
		
		public System.Data.Linq.Table<Cash_param> Cash_params
		{
			get
			{
				return this.GetTable<Cash_param>();
			}
		}
		
		public System.Data.Linq.Table<Classif_depart> Classif_departs
		{
			get
			{
				return this.GetTable<Classif_depart>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Group_devices")]
	public partial class Group_device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_group_devices;
		
		private string _Name_group_devices;
		
		private int _max_tran_rec;
		
		private string _keyboard_card;
		
		private EntitySet<Cash_param> _Cash_params;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_group_devicesChanging(int value);
    partial void Onid_group_devicesChanged();
    partial void OnName_group_devicesChanging(string value);
    partial void OnName_group_devicesChanged();
    partial void Onmax_tran_recChanging(int value);
    partial void Onmax_tran_recChanged();
    partial void Onkeyboard_cardChanging(string value);
    partial void Onkeyboard_cardChanged();
    #endregion
		
		public Group_device()
		{
			this._Cash_params = new EntitySet<Cash_param>(new Action<Cash_param>(this.attach_Cash_params), new Action<Cash_param>(this.detach_Cash_params));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_group_devices", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_group_devices
		{
			get
			{
				return this._id_group_devices;
			}
			set
			{
				if ((this._id_group_devices != value))
				{
					this.Onid_group_devicesChanging(value);
					this.SendPropertyChanging();
					this._id_group_devices = value;
					this.SendPropertyChanged("id_group_devices");
					this.Onid_group_devicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_group_devices", DbType="VarChar(40)")]
		public string Name_group_devices
		{
			get
			{
				return this._Name_group_devices;
			}
			set
			{
				if ((this._Name_group_devices != value))
				{
					this.OnName_group_devicesChanging(value);
					this.SendPropertyChanging();
					this._Name_group_devices = value;
					this.SendPropertyChanged("Name_group_devices");
					this.OnName_group_devicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_tran_rec", DbType="Int NOT NULL")]
		public int max_tran_rec
		{
			get
			{
				return this._max_tran_rec;
			}
			set
			{
				if ((this._max_tran_rec != value))
				{
					this.Onmax_tran_recChanging(value);
					this.SendPropertyChanging();
					this._max_tran_rec = value;
					this.SendPropertyChanged("max_tran_rec");
					this.Onmax_tran_recChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyboard_card", DbType="VarChar(100)")]
		public string keyboard_card
		{
			get
			{
				return this._keyboard_card;
			}
			set
			{
				if ((this._keyboard_card != value))
				{
					this.Onkeyboard_cardChanging(value);
					this.SendPropertyChanging();
					this._keyboard_card = value;
					this.SendPropertyChanged("keyboard_card");
					this.Onkeyboard_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Group_device_Cash_param", Storage="_Cash_params", ThisKey="id_group_devices", OtherKey="id_group_devices")]
		public EntitySet<Cash_param> Cash_params
		{
			get
			{
				return this._Cash_params;
			}
			set
			{
				this._Cash_params.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cash_params(Cash_param entity)
		{
			this.SendPropertyChanging();
			entity.Group_device = this;
		}
		
		private void detach_Cash_params(Cash_param entity)
		{
			this.SendPropertyChanging();
			entity.Group_device = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Devices")]
	public partial class Device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_device;
		
		private System.Nullable<int> _SHOPINDEX;
		
		private System.Nullable<int> _id_type_device;
		
		private string _name_device;
		
		private string _host_device;
		
		private System.Nullable<int> _state_device;
		
		private System.Nullable<int> _dataReady;
		
		private System.Nullable<int> _max_tran_rec;
		
		private System.Nullable<int> _ok_accept_data;
		
		private int _num_device;
		
		private System.Nullable<int> _id_model;
		
		private System.Nullable<int> _id_group_devices;
		
		private string _host_server;
		
		private System.Nullable<int> _need_reinit;
		
		private int _is_local_device;
		
		private int _is_loadable;
		
		private int _is_batch_mode;
		
		private string _name_db;
		
		private string _emailAddress;
		
		private System.Nullable<decimal> _price_diff;
		
		private string _user_name;
		
		private string _password;
		
		private System.Nullable<int> _num_depart_default;
		
		private int _upd_state;
		
		private string _upd_message;
		
		private string _version;
		
		private System.Nullable<int> _id_cash_device;
		
		private System.Nullable<System.DateTime> _last_load_time;
		
		private System.Nullable<int> _id_parent;
		
		private int _counter;
		
		private System.Nullable<int> _restart_flag;
		
		private EntitySet<Device> _Devices;
		
		private EntityRef<Device> _Device1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_deviceChanging(int value);
    partial void Onid_deviceChanged();
    partial void OnSHOPINDEXChanging(System.Nullable<int> value);
    partial void OnSHOPINDEXChanged();
    partial void Onid_type_deviceChanging(System.Nullable<int> value);
    partial void Onid_type_deviceChanged();
    partial void Onname_deviceChanging(string value);
    partial void Onname_deviceChanged();
    partial void Onhost_deviceChanging(string value);
    partial void Onhost_deviceChanged();
    partial void Onstate_deviceChanging(System.Nullable<int> value);
    partial void Onstate_deviceChanged();
    partial void OndataReadyChanging(System.Nullable<int> value);
    partial void OndataReadyChanged();
    partial void Onmax_tran_recChanging(System.Nullable<int> value);
    partial void Onmax_tran_recChanged();
    partial void Onok_accept_dataChanging(System.Nullable<int> value);
    partial void Onok_accept_dataChanged();
    partial void Onnum_deviceChanging(int value);
    partial void Onnum_deviceChanged();
    partial void Onid_modelChanging(System.Nullable<int> value);
    partial void Onid_modelChanged();
    partial void Onid_group_devicesChanging(System.Nullable<int> value);
    partial void Onid_group_devicesChanged();
    partial void Onhost_serverChanging(string value);
    partial void Onhost_serverChanged();
    partial void Onneed_reinitChanging(System.Nullable<int> value);
    partial void Onneed_reinitChanged();
    partial void Onis_local_deviceChanging(int value);
    partial void Onis_local_deviceChanged();
    partial void Onis_loadableChanging(int value);
    partial void Onis_loadableChanged();
    partial void Onis_batch_modeChanging(int value);
    partial void Onis_batch_modeChanged();
    partial void Onname_dbChanging(string value);
    partial void Onname_dbChanged();
    partial void OnemailAddressChanging(string value);
    partial void OnemailAddressChanged();
    partial void Onprice_diffChanging(System.Nullable<decimal> value);
    partial void Onprice_diffChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onnum_depart_defaultChanging(System.Nullable<int> value);
    partial void Onnum_depart_defaultChanged();
    partial void Onupd_stateChanging(int value);
    partial void Onupd_stateChanged();
    partial void Onupd_messageChanging(string value);
    partial void Onupd_messageChanged();
    partial void OnversionChanging(string value);
    partial void OnversionChanged();
    partial void Onid_cash_deviceChanging(System.Nullable<int> value);
    partial void Onid_cash_deviceChanged();
    partial void Onlast_load_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_load_timeChanged();
    partial void Onid_parentChanging(System.Nullable<int> value);
    partial void Onid_parentChanged();
    partial void OncounterChanging(int value);
    partial void OncounterChanged();
    partial void Onrestart_flagChanging(System.Nullable<int> value);
    partial void Onrestart_flagChanged();
    #endregion
		
		public Device()
		{
			this._Devices = new EntitySet<Device>(new Action<Device>(this.attach_Devices), new Action<Device>(this.detach_Devices));
			this._Device1 = default(EntityRef<Device>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_device", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_device
		{
			get
			{
				return this._id_device;
			}
			set
			{
				if ((this._id_device != value))
				{
					this.Onid_deviceChanging(value);
					this.SendPropertyChanging();
					this._id_device = value;
					this.SendPropertyChanged("id_device");
					this.Onid_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOPINDEX", DbType="Int")]
		public System.Nullable<int> SHOPINDEX
		{
			get
			{
				return this._SHOPINDEX;
			}
			set
			{
				if ((this._SHOPINDEX != value))
				{
					this.OnSHOPINDEXChanging(value);
					this.SendPropertyChanging();
					this._SHOPINDEX = value;
					this.SendPropertyChanged("SHOPINDEX");
					this.OnSHOPINDEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type_device", DbType="Int")]
		public System.Nullable<int> id_type_device
		{
			get
			{
				return this._id_type_device;
			}
			set
			{
				if ((this._id_type_device != value))
				{
					this.Onid_type_deviceChanging(value);
					this.SendPropertyChanging();
					this._id_type_device = value;
					this.SendPropertyChanged("id_type_device");
					this.Onid_type_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_device", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string name_device
		{
			get
			{
				return this._name_device;
			}
			set
			{
				if ((this._name_device != value))
				{
					this.Onname_deviceChanging(value);
					this.SendPropertyChanging();
					this._name_device = value;
					this.SendPropertyChanged("name_device");
					this.Onname_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_device", DbType="VarChar(900) NOT NULL", CanBeNull=false)]
		public string host_device
		{
			get
			{
				return this._host_device;
			}
			set
			{
				if ((this._host_device != value))
				{
					this.Onhost_deviceChanging(value);
					this.SendPropertyChanging();
					this._host_device = value;
					this.SendPropertyChanged("host_device");
					this.Onhost_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_device", DbType="Int")]
		public System.Nullable<int> state_device
		{
			get
			{
				return this._state_device;
			}
			set
			{
				if ((this._state_device != value))
				{
					this.Onstate_deviceChanging(value);
					this.SendPropertyChanging();
					this._state_device = value;
					this.SendPropertyChanged("state_device");
					this.Onstate_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataReady", DbType="Int")]
		public System.Nullable<int> dataReady
		{
			get
			{
				return this._dataReady;
			}
			set
			{
				if ((this._dataReady != value))
				{
					this.OndataReadyChanging(value);
					this.SendPropertyChanging();
					this._dataReady = value;
					this.SendPropertyChanged("dataReady");
					this.OndataReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_tran_rec", DbType="Int")]
		public System.Nullable<int> max_tran_rec
		{
			get
			{
				return this._max_tran_rec;
			}
			set
			{
				if ((this._max_tran_rec != value))
				{
					this.Onmax_tran_recChanging(value);
					this.SendPropertyChanging();
					this._max_tran_rec = value;
					this.SendPropertyChanged("max_tran_rec");
					this.Onmax_tran_recChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ok_accept_data", DbType="Int")]
		public System.Nullable<int> ok_accept_data
		{
			get
			{
				return this._ok_accept_data;
			}
			set
			{
				if ((this._ok_accept_data != value))
				{
					this.Onok_accept_dataChanging(value);
					this.SendPropertyChanging();
					this._ok_accept_data = value;
					this.SendPropertyChanged("ok_accept_data");
					this.Onok_accept_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_device", DbType="Int NOT NULL")]
		public int num_device
		{
			get
			{
				return this._num_device;
			}
			set
			{
				if ((this._num_device != value))
				{
					this.Onnum_deviceChanging(value);
					this.SendPropertyChanging();
					this._num_device = value;
					this.SendPropertyChanged("num_device");
					this.Onnum_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_model", DbType="Int")]
		public System.Nullable<int> id_model
		{
			get
			{
				return this._id_model;
			}
			set
			{
				if ((this._id_model != value))
				{
					this.Onid_modelChanging(value);
					this.SendPropertyChanging();
					this._id_model = value;
					this.SendPropertyChanged("id_model");
					this.Onid_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_group_devices", DbType="Int")]
		public System.Nullable<int> id_group_devices
		{
			get
			{
				return this._id_group_devices;
			}
			set
			{
				if ((this._id_group_devices != value))
				{
					this.Onid_group_devicesChanging(value);
					this.SendPropertyChanging();
					this._id_group_devices = value;
					this.SendPropertyChanged("id_group_devices");
					this.Onid_group_devicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host_server", DbType="VarChar(40)")]
		public string host_server
		{
			get
			{
				return this._host_server;
			}
			set
			{
				if ((this._host_server != value))
				{
					this.Onhost_serverChanging(value);
					this.SendPropertyChanging();
					this._host_server = value;
					this.SendPropertyChanged("host_server");
					this.Onhost_serverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_need_reinit", DbType="Int")]
		public System.Nullable<int> need_reinit
		{
			get
			{
				return this._need_reinit;
			}
			set
			{
				if ((this._need_reinit != value))
				{
					this.Onneed_reinitChanging(value);
					this.SendPropertyChanging();
					this._need_reinit = value;
					this.SendPropertyChanged("need_reinit");
					this.Onneed_reinitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_local_device", DbType="Int NOT NULL")]
		public int is_local_device
		{
			get
			{
				return this._is_local_device;
			}
			set
			{
				if ((this._is_local_device != value))
				{
					this.Onis_local_deviceChanging(value);
					this.SendPropertyChanging();
					this._is_local_device = value;
					this.SendPropertyChanged("is_local_device");
					this.Onis_local_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_loadable", DbType="Int NOT NULL")]
		public int is_loadable
		{
			get
			{
				return this._is_loadable;
			}
			set
			{
				if ((this._is_loadable != value))
				{
					this.Onis_loadableChanging(value);
					this.SendPropertyChanging();
					this._is_loadable = value;
					this.SendPropertyChanged("is_loadable");
					this.Onis_loadableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_batch_mode", DbType="Int NOT NULL")]
		public int is_batch_mode
		{
			get
			{
				return this._is_batch_mode;
			}
			set
			{
				if ((this._is_batch_mode != value))
				{
					this.Onis_batch_modeChanging(value);
					this.SendPropertyChanging();
					this._is_batch_mode = value;
					this.SendPropertyChanged("is_batch_mode");
					this.Onis_batch_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_db", DbType="VarChar(50)")]
		public string name_db
		{
			get
			{
				return this._name_db;
			}
			set
			{
				if ((this._name_db != value))
				{
					this.Onname_dbChanging(value);
					this.SendPropertyChanging();
					this._name_db = value;
					this.SendPropertyChanged("name_db");
					this.Onname_dbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAddress", DbType="VarChar(50)")]
		public string emailAddress
		{
			get
			{
				return this._emailAddress;
			}
			set
			{
				if ((this._emailAddress != value))
				{
					this.OnemailAddressChanging(value);
					this.SendPropertyChanging();
					this._emailAddress = value;
					this.SendPropertyChanged("emailAddress");
					this.OnemailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_diff", DbType="Decimal(19,2)")]
		public System.Nullable<decimal> price_diff
		{
			get
			{
				return this._price_diff;
			}
			set
			{
				if ((this._price_diff != value))
				{
					this.Onprice_diffChanging(value);
					this.SendPropertyChanging();
					this._price_diff = value;
					this.SendPropertyChanged("price_diff");
					this.Onprice_diffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_depart_default", DbType="Int")]
		public System.Nullable<int> num_depart_default
		{
			get
			{
				return this._num_depart_default;
			}
			set
			{
				if ((this._num_depart_default != value))
				{
					this.Onnum_depart_defaultChanging(value);
					this.SendPropertyChanging();
					this._num_depart_default = value;
					this.SendPropertyChanged("num_depart_default");
					this.Onnum_depart_defaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upd_state", DbType="Int NOT NULL")]
		public int upd_state
		{
			get
			{
				return this._upd_state;
			}
			set
			{
				if ((this._upd_state != value))
				{
					this.Onupd_stateChanging(value);
					this.SendPropertyChanging();
					this._upd_state = value;
					this.SendPropertyChanged("upd_state");
					this.Onupd_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upd_message", DbType="VarChar(MAX)")]
		public string upd_message
		{
			get
			{
				return this._upd_message;
			}
			set
			{
				if ((this._upd_message != value))
				{
					this.Onupd_messageChanging(value);
					this.SendPropertyChanging();
					this._upd_message = value;
					this.SendPropertyChanged("upd_message");
					this.Onupd_messageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this.OnversionChanging(value);
					this.SendPropertyChanging();
					this._version = value;
					this.SendPropertyChanged("version");
					this.OnversionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cash_device", DbType="Int")]
		public System.Nullable<int> id_cash_device
		{
			get
			{
				return this._id_cash_device;
			}
			set
			{
				if ((this._id_cash_device != value))
				{
					this.Onid_cash_deviceChanging(value);
					this.SendPropertyChanging();
					this._id_cash_device = value;
					this.SendPropertyChanged("id_cash_device");
					this.Onid_cash_deviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_load_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_load_time
		{
			get
			{
				return this._last_load_time;
			}
			set
			{
				if ((this._last_load_time != value))
				{
					this.Onlast_load_timeChanging(value);
					this.SendPropertyChanging();
					this._last_load_time = value;
					this.SendPropertyChanged("last_load_time");
					this.Onlast_load_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_parent", DbType="Int")]
		public System.Nullable<int> id_parent
		{
			get
			{
				return this._id_parent;
			}
			set
			{
				if ((this._id_parent != value))
				{
					if (this._Device1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_parentChanging(value);
					this.SendPropertyChanging();
					this._id_parent = value;
					this.SendPropertyChanged("id_parent");
					this.Onid_parentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counter", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int counter
		{
			get
			{
				return this._counter;
			}
			set
			{
				if ((this._counter != value))
				{
					this.OncounterChanging(value);
					this.SendPropertyChanging();
					this._counter = value;
					this.SendPropertyChanged("counter");
					this.OncounterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restart_flag", DbType="Int")]
		public System.Nullable<int> restart_flag
		{
			get
			{
				return this._restart_flag;
			}
			set
			{
				if ((this._restart_flag != value))
				{
					this.Onrestart_flagChanging(value);
					this.SendPropertyChanging();
					this._restart_flag = value;
					this.SendPropertyChanged("restart_flag");
					this.Onrestart_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Device_Device", Storage="_Devices", ThisKey="id_device", OtherKey="id_parent")]
		public EntitySet<Device> Devices
		{
			get
			{
				return this._Devices;
			}
			set
			{
				this._Devices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Device_Device", Storage="_Device1", ThisKey="id_parent", OtherKey="id_device", IsForeignKey=true)]
		public Device Device1
		{
			get
			{
				return this._Device1.Entity;
			}
			set
			{
				Device previousValue = this._Device1.Entity;
				if (((previousValue != value) 
							|| (this._Device1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Device1.Entity = null;
						previousValue.Devices.Remove(this);
					}
					this._Device1.Entity = value;
					if ((value != null))
					{
						value.Devices.Add(this);
						this._id_parent = value.id_device;
					}
					else
					{
						this._id_parent = default(Nullable<int>);
					}
					this.SendPropertyChanged("Device1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Devices(Device entity)
		{
			this.SendPropertyChanging();
			entity.Device1 = this;
		}
		
		private void detach_Devices(Device entity)
		{
			this.SendPropertyChanging();
			entity.Device1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Str_cash_params")]
	public partial class Str_cash_param : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_str_cash_param;
		
		private string _name_str_cash_param;
		
		private string _mnem_str_cash_param;
		
		private string _description;
		
		private System.Nullable<int> _type_param;
		
		private System.Nullable<int> _parent;
		
		private int _unused;
		
		private EntitySet<Cash_param> _Cash_params;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_str_cash_paramChanging(int value);
    partial void Onid_str_cash_paramChanged();
    partial void Onname_str_cash_paramChanging(string value);
    partial void Onname_str_cash_paramChanged();
    partial void Onmnem_str_cash_paramChanging(string value);
    partial void Onmnem_str_cash_paramChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ontype_paramChanging(System.Nullable<int> value);
    partial void Ontype_paramChanged();
    partial void OnparentChanging(System.Nullable<int> value);
    partial void OnparentChanged();
    partial void OnunusedChanging(int value);
    partial void OnunusedChanged();
    #endregion
		
		public Str_cash_param()
		{
			this._Cash_params = new EntitySet<Cash_param>(new Action<Cash_param>(this.attach_Cash_params), new Action<Cash_param>(this.detach_Cash_params));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_str_cash_param", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_str_cash_param
		{
			get
			{
				return this._id_str_cash_param;
			}
			set
			{
				if ((this._id_str_cash_param != value))
				{
					this.Onid_str_cash_paramChanging(value);
					this.SendPropertyChanging();
					this._id_str_cash_param = value;
					this.SendPropertyChanged("id_str_cash_param");
					this.Onid_str_cash_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_str_cash_param", DbType="VarChar(500)")]
		public string name_str_cash_param
		{
			get
			{
				return this._name_str_cash_param;
			}
			set
			{
				if ((this._name_str_cash_param != value))
				{
					this.Onname_str_cash_paramChanging(value);
					this.SendPropertyChanging();
					this._name_str_cash_param = value;
					this.SendPropertyChanged("name_str_cash_param");
					this.Onname_str_cash_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mnem_str_cash_param", DbType="VarChar(50)")]
		public string mnem_str_cash_param
		{
			get
			{
				return this._mnem_str_cash_param;
			}
			set
			{
				if ((this._mnem_str_cash_param != value))
				{
					this.Onmnem_str_cash_paramChanging(value);
					this.SendPropertyChanging();
					this._mnem_str_cash_param = value;
					this.SendPropertyChanged("mnem_str_cash_param");
					this.Onmnem_str_cash_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_param", DbType="Int")]
		public System.Nullable<int> type_param
		{
			get
			{
				return this._type_param;
			}
			set
			{
				if ((this._type_param != value))
				{
					this.Ontype_paramChanging(value);
					this.SendPropertyChanging();
					this._type_param = value;
					this.SendPropertyChanged("type_param");
					this.Ontype_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unused", DbType="Int NOT NULL")]
		public int unused
		{
			get
			{
				return this._unused;
			}
			set
			{
				if ((this._unused != value))
				{
					this.OnunusedChanging(value);
					this.SendPropertyChanging();
					this._unused = value;
					this.SendPropertyChanged("unused");
					this.OnunusedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Str_cash_param_Cash_param", Storage="_Cash_params", ThisKey="id_str_cash_param", OtherKey="id_str_cash_param")]
		public EntitySet<Cash_param> Cash_params
		{
			get
			{
				return this._Cash_params;
			}
			set
			{
				this._Cash_params.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cash_params(Cash_param entity)
		{
			this.SendPropertyChanging();
			entity.Str_cash_param = this;
		}
		
		private void detach_Cash_params(Cash_param entity)
		{
			this.SendPropertyChanging();
			entity.Str_cash_param = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cash_params")]
	public partial class Cash_param : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _value_param;
		
		private int _id_group_devices;
		
		private int _id_str_cash_param;
		
		private string _value_blob;
		
		private int _state;
		
		private EntityRef<Group_device> _Group_device;
		
		private EntityRef<Str_cash_param> _Str_cash_param;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvalue_paramChanging(string value);
    partial void Onvalue_paramChanged();
    partial void Onid_group_devicesChanging(int value);
    partial void Onid_group_devicesChanged();
    partial void Onid_str_cash_paramChanging(int value);
    partial void Onid_str_cash_paramChanged();
    partial void Onvalue_blobChanging(string value);
    partial void Onvalue_blobChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    #endregion
		
		public Cash_param()
		{
			this._Group_device = default(EntityRef<Group_device>);
			this._Str_cash_param = default(EntityRef<Str_cash_param>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value_param", DbType="VarChar(50)")]
		public string value_param
		{
			get
			{
				return this._value_param;
			}
			set
			{
				if ((this._value_param != value))
				{
					this.Onvalue_paramChanging(value);
					this.SendPropertyChanging();
					this._value_param = value;
					this.SendPropertyChanged("value_param");
					this.Onvalue_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_group_devices", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_group_devices
		{
			get
			{
				return this._id_group_devices;
			}
			set
			{
				if ((this._id_group_devices != value))
				{
					if (this._Group_device.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_group_devicesChanging(value);
					this.SendPropertyChanging();
					this._id_group_devices = value;
					this.SendPropertyChanged("id_group_devices");
					this.Onid_group_devicesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_str_cash_param", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_str_cash_param
		{
			get
			{
				return this._id_str_cash_param;
			}
			set
			{
				if ((this._id_str_cash_param != value))
				{
					if (this._Str_cash_param.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_str_cash_paramChanging(value);
					this.SendPropertyChanging();
					this._id_str_cash_param = value;
					this.SendPropertyChanged("id_str_cash_param");
					this.Onid_str_cash_paramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value_blob", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string value_blob
		{
			get
			{
				return this._value_blob;
			}
			set
			{
				if ((this._value_blob != value))
				{
					this.Onvalue_blobChanging(value);
					this.SendPropertyChanging();
					this._value_blob = value;
					this.SendPropertyChanged("value_blob");
					this.Onvalue_blobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Group_device_Cash_param", Storage="_Group_device", ThisKey="id_group_devices", OtherKey="id_group_devices", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Group_device Group_device
		{
			get
			{
				return this._Group_device.Entity;
			}
			set
			{
				Group_device previousValue = this._Group_device.Entity;
				if (((previousValue != value) 
							|| (this._Group_device.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Group_device.Entity = null;
						previousValue.Cash_params.Remove(this);
					}
					this._Group_device.Entity = value;
					if ((value != null))
					{
						value.Cash_params.Add(this);
						this._id_group_devices = value.id_group_devices;
					}
					else
					{
						this._id_group_devices = default(int);
					}
					this.SendPropertyChanged("Group_device");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Str_cash_param_Cash_param", Storage="_Str_cash_param", ThisKey="id_str_cash_param", OtherKey="id_str_cash_param", IsForeignKey=true)]
		public Str_cash_param Str_cash_param
		{
			get
			{
				return this._Str_cash_param.Entity;
			}
			set
			{
				Str_cash_param previousValue = this._Str_cash_param.Entity;
				if (((previousValue != value) 
							|| (this._Str_cash_param.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Str_cash_param.Entity = null;
						previousValue.Cash_params.Remove(this);
					}
					this._Str_cash_param.Entity = value;
					if ((value != null))
					{
						value.Cash_params.Add(this);
						this._id_str_cash_param = value.id_str_cash_param;
					}
					else
					{
						this._id_str_cash_param = default(int);
					}
					this.SendPropertyChanged("Str_cash_param");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Classif_depart")]
	public partial class Classif_depart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_depart;
		
		private System.Nullable<int> _id_parent;
		
		private string _name_depart;
		
		private System.Nullable<int> _num_depart;
		
		private int _bo_number;
		
		private string _client_id;
		
		private string _egais_prop;
		
		private string _ofd_prop;
		
		private string _bpa_prop;
		
		private EntitySet<Classif_depart> _Classif_departs;
		
		private EntityRef<Classif_depart> _Classif_depart1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_departChanging(int value);
    partial void Onid_departChanged();
    partial void Onid_parentChanging(System.Nullable<int> value);
    partial void Onid_parentChanged();
    partial void Onname_departChanging(string value);
    partial void Onname_departChanged();
    partial void Onnum_departChanging(System.Nullable<int> value);
    partial void Onnum_departChanged();
    partial void Onbo_numberChanging(int value);
    partial void Onbo_numberChanged();
    partial void Onclient_idChanging(string value);
    partial void Onclient_idChanged();
    partial void Onegais_propChanging(string value);
    partial void Onegais_propChanged();
    partial void Onofd_propChanging(string value);
    partial void Onofd_propChanged();
    partial void Onbpa_propChanging(string value);
    partial void Onbpa_propChanged();
    #endregion
		
		public Classif_depart()
		{
			this._Classif_departs = new EntitySet<Classif_depart>(new Action<Classif_depart>(this.attach_Classif_departs), new Action<Classif_depart>(this.detach_Classif_departs));
			this._Classif_depart1 = default(EntityRef<Classif_depart>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_depart", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_depart
		{
			get
			{
				return this._id_depart;
			}
			set
			{
				if ((this._id_depart != value))
				{
					this.Onid_departChanging(value);
					this.SendPropertyChanging();
					this._id_depart = value;
					this.SendPropertyChanged("id_depart");
					this.Onid_departChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_parent", DbType="Int")]
		public System.Nullable<int> id_parent
		{
			get
			{
				return this._id_parent;
			}
			set
			{
				if ((this._id_parent != value))
				{
					if (this._Classif_depart1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_parentChanging(value);
					this.SendPropertyChanging();
					this._id_parent = value;
					this.SendPropertyChanged("id_parent");
					this.Onid_parentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_depart", DbType="NVarChar(100)")]
		public string name_depart
		{
			get
			{
				return this._name_depart;
			}
			set
			{
				if ((this._name_depart != value))
				{
					this.Onname_departChanging(value);
					this.SendPropertyChanging();
					this._name_depart = value;
					this.SendPropertyChanged("name_depart");
					this.Onname_departChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_depart", DbType="Int")]
		public System.Nullable<int> num_depart
		{
			get
			{
				return this._num_depart;
			}
			set
			{
				if ((this._num_depart != value))
				{
					this.Onnum_departChanging(value);
					this.SendPropertyChanging();
					this._num_depart = value;
					this.SendPropertyChanged("num_depart");
					this.Onnum_departChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bo_number", DbType="Int NOT NULL")]
		public int bo_number
		{
			get
			{
				return this._bo_number;
			}
			set
			{
				if ((this._bo_number != value))
				{
					this.Onbo_numberChanging(value);
					this.SendPropertyChanging();
					this._bo_number = value;
					this.SendPropertyChanged("bo_number");
					this.Onbo_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_client_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string client_id
		{
			get
			{
				return this._client_id;
			}
			set
			{
				if ((this._client_id != value))
				{
					this.Onclient_idChanging(value);
					this.SendPropertyChanging();
					this._client_id = value;
					this.SendPropertyChanged("client_id");
					this.Onclient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_egais_prop", DbType="NVarChar(MAX)")]
		public string egais_prop
		{
			get
			{
				return this._egais_prop;
			}
			set
			{
				if ((this._egais_prop != value))
				{
					this.Onegais_propChanging(value);
					this.SendPropertyChanging();
					this._egais_prop = value;
					this.SendPropertyChanged("egais_prop");
					this.Onegais_propChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ofd_prop", DbType="NVarChar(MAX)")]
		public string ofd_prop
		{
			get
			{
				return this._ofd_prop;
			}
			set
			{
				if ((this._ofd_prop != value))
				{
					this.Onofd_propChanging(value);
					this.SendPropertyChanging();
					this._ofd_prop = value;
					this.SendPropertyChanged("ofd_prop");
					this.Onofd_propChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bpa_prop", DbType="NVarChar(4000)")]
		public string bpa_prop
		{
			get
			{
				return this._bpa_prop;
			}
			set
			{
				if ((this._bpa_prop != value))
				{
					this.Onbpa_propChanging(value);
					this.SendPropertyChanging();
					this._bpa_prop = value;
					this.SendPropertyChanged("bpa_prop");
					this.Onbpa_propChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Classif_depart_Classif_depart", Storage="_Classif_departs", ThisKey="id_depart", OtherKey="id_parent")]
		public EntitySet<Classif_depart> Classif_departs
		{
			get
			{
				return this._Classif_departs;
			}
			set
			{
				this._Classif_departs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Classif_depart_Classif_depart", Storage="_Classif_depart1", ThisKey="id_parent", OtherKey="id_depart", IsForeignKey=true)]
		public Classif_depart Classif_depart1
		{
			get
			{
				return this._Classif_depart1.Entity;
			}
			set
			{
				Classif_depart previousValue = this._Classif_depart1.Entity;
				if (((previousValue != value) 
							|| (this._Classif_depart1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Classif_depart1.Entity = null;
						previousValue.Classif_departs.Remove(this);
					}
					this._Classif_depart1.Entity = value;
					if ((value != null))
					{
						value.Classif_departs.Add(this);
						this._id_parent = value.id_depart;
					}
					else
					{
						this._id_parent = default(Nullable<int>);
					}
					this.SendPropertyChanged("Classif_depart1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Classif_departs(Classif_depart entity)
		{
			this.SendPropertyChanging();
			entity.Classif_depart1 = this;
		}
		
		private void detach_Classif_departs(Classif_depart entity)
		{
			this.SendPropertyChanging();
			entity.Classif_depart1 = null;
		}
	}
}
#pragma warning restore 1591
